# Generated by Django 4.1 on 2023-05-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_twins_service', '0003_alter_snippet_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='highlighted',
            new_name='highlight',
        ),
    ]
